---
extends: eslint:recommended

env:
  es6: true
  node: true

parser: "babel-eslint"

parserOptions:
  sourceType: "module"

rules:
  # Possible Errors
  no-extra-parens: 2
  no-unexpected-multiline: 2

  # Best Practices
  curly: 2
  default-case: 2
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-case-declarations: 2
  no-else-return: 2
  no-empty-pattern: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-floating-decimal: 2
  no-implied-eval: 2
  no-iterator: 2
  no-labels: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-native-reassign: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-proto: 2
  no-return-assign: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-void: 2
  no-with: 2
  radix: [2, "as-needed"]
  wrap-iife: [2, "outside"]
  yoda: 2

  # Variables
  init-declarations: [2, "always"]
  no-catch-shadow: 2
  no-shadow-restricted-names: 2
  no-undef-init: 2

  # Stylistic Issues
  array-bracket-spacing: [2, "never"]
  block-spacing: [2, "always"]
  camelcase: [2, {properties: "always"}]
  comma-spacing: [2, {before: false, after: true}]
  computed-property-spacing: [2, "never"]
  eol-last: 2
  indent: [2, 4, {"SwitchCase": 1}]
  jsx-quotes: [2, "prefer-double"]
  key-spacing: [2, {beforeColon: false, afterColon: true, mode: "strict"}]
  linebreak-style: [2, "unix"]
  max-len: [2, 120, 4]
  max-params: [2, 5]
  max-statements: [2, 20]
  new-cap: [2, {newIsCap: true, capIsNew: false}]
  new-parens: 2
  no-array-constructor: 2
  no-lonely-if: 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines: [2, {max: 1, maxEOF: 1}]
  no-new-object: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-unneeded-ternary: [2, {defaultAssignment: true }]
  object-curly-spacing: [2, "always"]
  one-var: [2, "never"]
  padded-blocks: [2, "never"]
  quote-props: [2, "consistent"]
  quotes: [2, "single", "avoid-escape"]
  semi-spacing: [2, {before: false, after: true}]
  semi: 2
  space-before-blocks: [2, "always"]
  space-before-function-paren: [2, "never"]
  space-in-parens: [2, "never"]
  space-infix-ops: [2, {int32Hint: false}]
  space-unary-ops: [1, { words: true, nonwords: false }]

  # ECMAScript 6
  arrow-spacing: [2, {before: true, after: true}]
  constructor-super: 2
  no-class-assign: 2
  no-const-assign: 2
  no-dupe-class-members: 2
  no-this-before-super: 2
  no-var: 2
  object-shorthand: [2, "always"]
  prefer-const: 2
  prefer-spread: 2
  prefer-template: 2
